[project]
name = "fnirs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jax==0.4.38",
    "matplotlib>=3.10.3",
    "ipython>=9.4.0",
    "astropy>=7.1.0",
    "pywavelets>=1.8.0",
    "statsmodels>=0.14.5",
]
